[package]
name = "ctor-codegen"
version = "0.1.0"
authors = ["Matt Mastracci <matthew@mastracci.com>"]
edition = "2018"
publish = false

[dependencies]
libc-print = "0.1.20"
syn = "2"
quote = "1"
proc-macro2 = "1"
paste = "1"
